#!/bin/sh

# Openwrt calls /usr/sbin/pppd with ip-up-script=/lib/netifd/ppp-up, ipv6-up-script/lib/netifd/ppp-up, ip-down-script=/lib/netifd/ppp-down, and ipv6-down-script/lib/netifd/ppp-down.
# ppp-up will call files in /etc/ppp/ip-up.d/* and ppp-down will call files in /etc/ppp/ip-down.d/*.
# Environment list:
# USEPEERDNS: use remove assigned dns servers
# IPLOCAL: local address
# IPREMOTE: remove address
# LLLOCAL:
# DNS1: dns server 1
# DNS2: dns server 2

# Script input arguments:
# 0: full script name
# 1: ppp interface name, Ex:pppoe-wan
# 2: ppp physical device name: Ex: nas0
# 3: speed
# 4: local address
# 5: remove address
# 6: interface section, Ex: wan

default_wan=`mng_cli get ARC_WAN_DefaultRouteIdx`
wan_type=`mng_cli get ARC_WAN_Type`
INTERFACE=$6
interface_section=${INTERFACE:0:3}
tmp_index=`echo ${INTERFACE:3:6} | awk '{printf "%d", $1}'`
wan_index=${wan_type}" "${tmp_index}
IFNAME=$1
echo "[ppp-down] INTERFACE:$INTERFACE, wan_index:$wan_index, IFNAME:$IFNAME" > /dev/console

pppoe_demand=`mng_cli get ARC_WAN_${wan_index}_PPP_OnDemand_PPPOE`
pptp_demand=`mng_cli get ARC_WAN_${wan_index}_PPP_OnDemand_PPTP`
l2tp_demand=`mng_cli get ARC_WAN_${wan_index}_PPP_OnDemand_L2TP`

abscfg set ARC_WAN_xy_TMP_PPP_GET_IP4_Addr ${wan_index} "0.0.0.0"
abscfg set ARC_WAN_xy_TMP_PPP_GET_IP4_Netmask ${wan_index} "0.0.0.0"
abscfg set ARC_WAN_xy_TMP_PPP_GET_IP4_Gateway ${wan_index} "0.0.0.0"
abscfg set ARC_WAN_xy_TMP_IP4_DNS_Runtime1 ${wan_index} ""
abscfg set ARC_WAN_xy_TMP_IP4_DNS_Runtime2 ${wan_index} ""
abscfg set ARC_WAN_xy_TMP_PPP_Status ${wan_index} "Disconnected"
abscfg set ARC_WAN_xy_TMP_Connect_Status ${wan_index} 0
abscfg set ARC_WAN_xy_TMP_Iface ${wan_index} ""
abscfg set ARC_WAN_TMP_IPv4_WAN_Ready 0
