#!/bin/sh

case "$1" in
	"CMD_BOOT" | "CMD_START" | "CMD_RESTART")
        	
	/usr/sbin/sip_config SIP_CORE_DialRule_CFGSync 

		;;

	"CMD_STOP")

		;;

	*)
		echo $0 'Phone_CFGSync          - notify brnsip '
		;;
esac